# Generated by Django 4.2.6 on 2023-11-07 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_site', '0006_products_created_at_productsraitings_productslikes'),
    ]

    operations = [
        migrations.CreateModel(
            name='E_mails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_mail', models.CharField(max_length=250)),
            ],
        ),
    ]
