# Generated by Django 4.2.6 on 2023-11-09 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_site', '0007_e_mails'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.TextField(max_length=250)),
            ],
        ),
        migrations.DeleteModel(
            name='E_mails',
        ),
    ]
